### ISSUE TITLE
error Command "@strapi/codemods" not found.

### ISSUE THREAD

**Issue by Martin-Eckleben** [strapi/codemods#27]
Hi Strapi Team,

Whenever I do:
`yarn @strapi/codemods migrate:plugin ./plugins/pluginname-v3/ ./plugins/pluginname-v4/`
(as documentation and the README.md of this repo state)

I get:
```
yarn run v1.22.18
error Command "@strapi/codemods" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But I did
`yarn add @strapi/codemods`
before successfully.

I'm doing something obviously stupid right? :D
Thank you kind stranger for your time and effort!

**Comment by markkaylor** [comment]
Hi @Martin-Eckleben you are absolutely not doing anything stupid :) 

The README needs to be updated it looks like the commands are not clear and in some cases wrong.

If you install the package in your Strapi application or plugin:
```
yarn add @strapi/codemods
```
Then you can run in your project:
```
yarn codemods
```
This comes from the bin command in the codemods `package.json` 

However I recommend you use `npx` and don't install the package in your project. For this you can run
```
npx @strapi/codemods
```
I am going to update the readme to use `npx` everywhere. I will also change the bin command to `strapi-codemods` instead of just `codemods`

 I'll leave this issue open until those changes have been merged and released.
