### ISSUE TITLE
Why does codemods create a `v3` folder?

### ISSUE THREAD

**Issue by nbro10** [strapi/codemods#55]
I have a folder called `v3`, which was generated by `codemods`. It seems that this folder contains the old code, but does it contain everything? What is it supposed to contain? In my case, it contains all main folders (so `admin`, `api`, `config`, `extensions` and `plugins`), except `public`. I suppose this is just created only as a backup and can be removed if we don't need to keep anything from our v3 app. Is that right?

Btw, in my case, the `plugins` folder was completely ignored (apparently). I suppose this is because the tool cannot automatically migrate plugins in general.

**Comment by markkaylor** [comment]
> I suppose this is just created only as a backup and can be removed if we don't need to keep anything from our v3 app. Is that right

This is correct.

> Btw, in my case, the plugins folder was completely ignored (apparently). I suppose this is because the tool cannot automatically migrate plugins in general.

Sorry it's been a while since I've worked in this repo but that sounds right. I don't think we setup the migrate application folder structure to also migrate local plugins. However I think it can be achieved by then running the migration script for each local plugin. 

As we are approaching v5 and a new upgrade tool is in development I do not believe we will invest in any improvements here. I hope it is not an inconvenience and thank your for your understanding. 

I'll close this issue but feel free to ask any other questions and I'll do my best to answer.

**Comment by nbro10** [comment]
@markkaylor Could this https://forum.strapi.io/t/v3-to-v4-codemods-not-working-when-strapi-in-github-monorepo/23256 at least be solved?

So, basically, the problem is that we can't use codemods to migrate a strapi app, which is in a subfolder of the git repository. The workaround is to create a dummy `.git` folder in that subfolder, then delete it after the migration. 

It doesn't seem like this would be difficult to fix given that this simple hack solves the problem
